### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Kulgar** [Kulgar/jira2redmine#18]
@meltzow: I did not find a way to contact you personally, so I'm posting here. I'd like to continue maintaining this project as I will certainly use it a lot from now on. 

Would you accept to transfer it to me?

Thanks :)

**Comment by meltzow** [comment]
hi,
yes, very cool. I will try to transfer it in some minutes.

**Comment by meltzow** [comment]
now you are requested ;-)

**Comment by Kulgar** [comment]
Thanks :)
